version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:80"
  redis:
    image: "vuejs-cookbook/dockerize-vuejs-app"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
        
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - "8089:8080"
